### ISSUE TITLE
[BUG-CRASH] Igniter

### ISSUE THREAD

**Issue by DWinze** [percivalalb/Trapcraft#10]
Hi,

I recently found a bug with the igniter. If you break the block below the fire the game crash and you lose your world.

**Comment by percivalalb** [comment]
I can not immediately recreate, can you provide logs?

**Comment by DWinze** [comment]
![image](https://user-images.githubusercontent.com/38311518/103373905-79b08380-4ad6-11eb-8d7a-4c08d1b0d2c7.png)


https://user-images.githubusercontent.com/38311518/103374137-14a95d80-4ad7-11eb-8d8b-4fa0bbd996e7.mp4

[debug.log](https://github.com/percivalalb/Trapcraft/files/5755318/debug.log)
[latest.log](https://github.com/percivalalb/Trapcraft/files/5755320/latest.log)

**Comment by percivalalb** [comment]
Should be fixed in v3.2.2+

**Comment by DWinze** [comment]
Nice !! ^^ good mod anw bro
