### ISSUE TITLE
1.18.1 Crashing do to FanTileEntity spawnParticles I think

### ISSUE THREAD

**Issue by EvilEtho** [percivalalb/Trapcraft#14]
Hope this is helpful with mod development.
This craft mostly happens when loading in to an area.

https://pastebin.com/HvXgZNKZ

**Comment by percivalalb** [comment]
I believe this is fixed in version 3.6.3 could you upgrade and check?

Many thanks

**Comment by percivalalb** [comment]
Assuming fixed, please do re-open if not
