### ISSUE TITLE
1.18.1 Crash when unloading a fan

### ISSUE THREAD

**Issue by EvergreenSystems** [percivalalb/Trapcraft#16]
Mod version: 1.18.1-3.6.0
Forge: 39.0.9
Optifine: no

This crash occurs when unloading a fan, in this case teleporting away using the waystones mod.

Debug log: [https://gist.github.com/Shedao-Shai/f303b3d6618d1b400d70de22bec4efd0](url)

Latest log: [https://gist.github.com/Shedao-Shai/8f249406770a63744640686ad1b3db03](url)

Crash log: [https://gist.github.com/Shedao-Shai/7b812a3ad7356e3cf636d749f9e90788](url)

**Comment by EvergreenSystems** [comment]
hm those gists didnt like to work, here are new links

Debug: https://gist.github.com/Shedao-Shai/1ab9b85c7e2515594c01ef69871f7445

Latest: https://gist.github.com/Shedao-Shai/440deba6f183031281430305c80f4371

Crash: https://gist.github.com/Shedao-Shai/77c0814fe6d55e1799473b1ae85d2eb4

**Comment by percivalalb** [comment]
I believe this is fixed in version 3.6.3 could you upgrade and check?

Many thanks

**Comment by EvergreenSystems** [comment]
This issue does seem to be fixed with the latest version, thank you!

(sorry for the delay, life happened)

**Comment by percivalalb** [comment]
Glad it did, closing :)
